### ISSUE TITLE
Is painting information useful in data files (geojson)?

### ISSUE THREAD

**Issue by cladjidane** [map-gl-indoor/map-gl-indoor#20]
Hi, thanks for this cool library ^^ I understand that the information in the geojson data about layer styles is not taken into account. I don't see anything in the code that allows you to manage a different display for certain features of the same type (room for example). Except in the example called "custom-styles" but that's different.

I would have imagined something that browses the array of features and, if the layout or painting information is present, executes a setPaintProperty / setLayoutProperty

Am I mistaken? 

**EDIT**

Maybe this solution would work, but that's a lot of expressions to process, given the number of layers + the number of potential properties. Any comments?

/src/style/default_layers.json
```
...
  {
    "filter": ["any", ["filter-==", "indoor", "room"]],
    "id": "indoor-rooms-borders",
    "type": "line",
    "source": "indoor",
    "paint": {
      "line-color": ["case", ["has", "line-color"], ["get", "line-color"], "#000"], // <- up
      "line-width": ["case", ["has", "line-width"], ["get", "line-width"], 3], // <- up
      "line-opacity": { "base": 1, "stops": [ [15, 0], [18, 1] ]
      }
    }
  },
...
```

**Comment by ThibaudM** [comment]
Hello :)
You can do it with data-driven properties like this: https://docs.mapbox.com/mapbox-gl-js/example/data-driven-lines/ (like in your edit)
From my knowledge, there is no "automatic method" to do it. 
In general, it's not a good practice to stylize data directly in the geojson. It's better to have custom properties in the geojson and use conditions in the style of each layer.
If it is ok for you, I prefer to close the issue because this enhancement is relative to maplibre/mapbox engine.

**Comment by cladjidane** [comment]
Ok, thanks!
