### ISSUE TITLE
Ability to render geojson without levels

### ISSUE THREAD

**Issue by heaven** [map-gl-indoor/map-gl-indoor#5]
We often work with files that don't have level information and represent just a single floor. We need the ability to set a default floor and just render all the features from a file.

**Comment by ThibaudM** [comment]
I am not sure I understand your question because:
- You can do it with this library. (If you mention the `level` property of your unique floor in the geojson features).
- You do not need this library to stylize a geojson source with layers without multi-level. (If you are interested in the default style applied by this lib, you will find it here: https://github.com/map-gl-indoor/map-gl-indoor/blob/main/src/style/default_layers.json).

Maybe you should provide more information about your geojson contents and what do you expect exactly?
